[package]
name = "jvoaq"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
latkerlo-jvotci = "1.0.9"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.118"
